title: Novanet UX - 2018 Winter Survey
tagline: Making Meaning out of Usability Testing - Unpacking a Discovery Layer
email: sandra.sawchuk@msvu.ca
description: 
baseurl: ""
url: "https://novanet-ux.github.io"
repository: novanet-ux/winter-2018

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: none

# Set encoding to UTF-8
encoding: utf-8
